services:
  # Backend Web Service
  - type: web
    name: totem-backend
    runtime: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: dpg-d4r536uuk2gs738114cg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: totem_database_5z32_user
      - key: DB_PASSWORD
        value: RiKUG5gajAuWxlfVZYnO9wMns0xBCw38
      - key: DB_NAME
        value: totem_database_5z32
      - key: DB_DIALECT
        value: postgres
      - key: JWT_SECRET
        generateValue: true
      - key: APP_ORIGIN
        value: https://totem-admin-bay.vercel.app,https://totem-admin.vercel.app
    autoDeploy: true
