services:
  # Backend Web Service
  - type: web
    name: totem-backend
    runtime: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: switchback.proxy.rlwy.net
      - key: DB_PORT
        value: 18664
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: JKwXRjsKuiXWlXaThpyJIgWRYctZqCki
      - key: DB_NAME
        value: railway
      - key: JWT_SECRET
        generateValue: true
      - key: APP_ORIGIN
        value: https://totem-admin.vercel.app
    autoDeploy: true
